### ISSUE TITLE
snippets not working

### ISSUE THREAD

**Issue by akshay34** [arandilopez/bootstrap3-snippets#2]
hi greetings,
                    I am Akshay from India,I was browsing through the packages in atom editor and found this package to be of great use and installed it.

But i am facing a problem the snippets do not seem to work at all for example when i key in  bs3-alert followed by tab instead of the snippet expanding a tag <bs3-alert> </bs3-alert> is created. Please do let me know how i should go about solving this issue. 

Thanks in advance...

**Comment by arandilopez** [comment]
Hi @akshay34, are you using emmet plugin?

**Comment by akshay34** [comment]
@arandilopez hi mate,yes i am using emmet plugin is it not possible for me to run both of them simultaneously.

**Comment by arandilopez** [comment]
Nope, emmet crash with almost all snippets plugins, maybe you have to tweak your configs to make them work together. [Check this out for some info or other issues of emmet.](https://github.com/emmetio/emmet-atom/issues/146)

**Comment by akshay34** [comment]
oh ok thank you...
